baseurl = "/"
languageCode = "en-us"
title = "StatusKit"

[permalinks]
  incidents = "/incidents/:year/:month/:day/:slug/"

[params]
  defaultLogo = "http://prosites.me/wp-content/uploads/2017/05/icon.png"
  faviconsPath = "/images/favicon/"

# List of systems monitored in this status page.
# You'll be able to change their status every time
# you open or update an incident.
# Example:
# systems = ["API", "CDN", "DNS", "Site delivery"]
systems = ["Website", "Sub-Sites", "Login System", "API", "Admin Dashboard"]
